name: gabrimatic_utils
description: A set of useful tools to make development more easily. A bunch of date utils, restart and exit app functions, string extensions and etc.
version: 0.0.4
author: Hossein Yousefpour <h.yusefpour@gmail.com>
homepage: https://github.com/gabrimatic/FlutterUtils

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  persian_date: ^0.1.5
  jalali_calendar: ^1.0.3+1
  persian_datetime_picker: ^1.0.7
  easy_localization: ^2.3.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: